# 头部菜单，title: link
menu:
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about
  Excel函数表: https://www.ocexa.cn:10003/d/s/734967737417211928/IxagvuBhy9eusNurwcIeusd2ypJ4xiNw-GSBgj1whMwo_


# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://music.163.com/song/media/outer/url?id=1386604074.mp3
    - http://music.163.com/song/media/outer/url?id=1983968838.mp3
    - http://music.163.com/song/media/outer/url?id=1475205240.mp3
    - http://music.163.com/song/media/outer/url?id=1329665666.mp3
    - http://music.163.com/song/media/outer/url?id=1329664866.mp3
    - http://music.163.com/song/media/outer/url?id=1965991637.mp3
    - http://music.163.com/song/media/outer/url?id=475073089.mp3
    - http://music.163.com/song/media/outer/url?id=1818613179.mp3
    - http://music.163.com/song/media/outer/url?id=1832606560.mp3
    - http://music.163.com/song/media/outer/url?id=1834950169.mp3
    - http://music.163.com/song/media/outer/url?id=1470255625.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover1.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover2.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover3.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover4.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover5.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover6.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover7.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover8.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover9.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover10.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover11.png
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover12.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover13.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover14.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover15.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover16.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover17.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover18.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover19.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover20.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover21.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover22.jpg
  - https://cdn.jsdelivr.net/gh/LngYan/CDN_Server/img/cover/cover23.jpg


# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    icon_bilibili: https://space.bilibili.com/2459286
    qq: img/qq.jpg
    wechat: /img/weixin.jpg
    twitter: https://twitter.com/CH_Lngyan
    github: https://github.com/LngYan
    NAS: https://www.ocexa.cn:5001
    email: mailto:a45611300@gmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'c2cb3305e9b43afef8ad'
    # 应用秘钥
    clientSecret: 'c6c5ed4ad679e0a71a9bceb3f7318dd6a384c672'
    # issue仓库名
    repo: 'LngYan.github.io'
    # Github名
    owner: 'LngYan'
    # Github名
    admin: ['LngYan']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: 冷焱

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

# 要使用版权信息可以在这配置并设定许可方式，可以从 https://creativecommons.org/about/cclicenses/ 查询
copyright:
    enable: false
    license: "CC BY-NC-ND"

# inject:
#  head:
    # - <link rel="stylesheet" href="/xxx.css">
#    - <script src="https://cdn.jsdelivr.net/gh/Weidows-projects/live2d-moc3/dist/live2dcubismcore.min.js"></script>
#    - <script src="https://cdn.jsdelivr.net/gh/Weidows-projects/live2d-moc3/dist/pixi.min.js"></script>
#    - <script src="https://cdn.jsdelivr.net/gh/Weidows-projects/live2d-moc3/dist/live2d.min.js"></script>
#  bottom:
    # - <script src="xxxx"></script>
#    -     <script>addEventListener("DOMContentLoaded",function(){let models=[{width:800,height:600,right:"0px",bottom:"0px",basePath:"live2d_models/",role:"lengyan",background:"",opacity:1,mobile:false,},];new Live2dLoader(models)});</script>

